server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
#  cloud:
#    config:
#      enabled: false
  application:
    name: eureka-client2

feign:
  hystrix:
    enabled: true

zuul:
  routes:
    users:
      path: /myuser/**
      serviceid: EUREKA-CLIENT
      stripPrefix: true  #主要是在浏览器地址上去除 忽略/myuser
    mybatis:
      path: /mybatis/**
      serviceid: MYBATIS2

ribbon:
  okhttp:
    enabled: true



